update githook

diff --git a/KubeSec-master/GitHook/pre-commit b/KubeSec-master/GitHook/pre-commit
--- a/KubeSec-master/GitHook/pre-commit
+++ b/KubeSec-master/GitHook/pre-commit
@@ -1,16 +1,54 @@
 #!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
 
-REPORT="report.csv"
-FILES=("constants.py" "graphtaint.py" "main.py" "parser.py" "scanner.py" "TEST_CONSTANTS.py" "TEST_GRAPH.py" "TEST_INTEGRATION.py" "TEST_PARSING.py" "TEST_SCANNING.py")
+# if git rev-parse --verify HEAD >/dev/null 2>&1
+# then
+# 	against=HEAD
+# else
+# 	# Initial commit: diff against an empty tree object
+# 	against=$(git hash-object -t tree /dev/null)
+# fi
 
-for file in "${FILES[@]}"; do
-    bandit -f csv "$file" | tail -n +2 >> "$REPORT" 
-done
+# If you want to allow non-ASCII filenames set this variable to true.
+# allownonascii=$(git config --type=bool hooks.allownonascii)
 
-# Check if the CSV report is empty, and if so, remove it
-if [ ! -s "$REPORT" ]; then
-    rm -f "$REPORT"
-fi
+# Redirect output to stderr.
+# exec 1>&2
 
-# Exit with success, assuming no issues were found
-exit 0
+# Cross platform projects tend to avoid non-ASCII filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+# if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	# test $(git diff --cached --name-only --diff-filter=A -z $against |
+	#   LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+# then
+	# cat <<\EOF
+# Error: Attempt to add a non-ASCII file name.
+
+# This can cause problems if you want to work with people on other platforms.
+
+# To be portable it is advisable to rename the file.
+
+# If you know what you are doing you can disable this check using:
+
+#   git config hooks.allownonascii true
+# EOF
+	# exit 1
+# fi
+
+# If there are whitespace errors, print the offending file names and fail.
+# exec git diff-index --check --cached $against --
+
+# Running python file scanner
+echo "Running bandit"
+bandit -r . -f csv -o bandit_results.csv
+echo "Bandit complete"
